# Generated by Django 3.2.5 on 2022-06-20 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('aparelhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aparelho',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
