# Generated by Django 3.2.5 on 2022-06-20 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('aparelhos', '0002_auto_20220620_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparelho',
            name='category',
        ),
        migrations.CreateModel(
            name='AparelhoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('aparelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparelhos.aparelho')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Categoria do Aparelho',
                'verbose_name_plural': 'Categoria do Aparelho',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='aparelho',
            name='category',
            field=models.ManyToManyField(blank=True, through='aparelhos.AparelhoCategory', to='categories.Category'),
        ),
    ]
