# Generated by Django 3.2.5 on 2022-06-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('aparelhos', '0003_auto_20220620_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparelho',
            name='category',
        ),
        migrations.AddField(
            model_name='aparelho',
            name='aparelho_category',
            field=models.ManyToManyField(blank=True, through='aparelhos.AparelhoCategory', to='categories.Category'),
        ),
    ]
